### ISSUE TITLE
documentation, yo

### ISSUE THREAD

**Issue by BrianHicks** [asteris-llc/hammer#13]
we don't have it. We need it.

**Comment by langston-barrett** [comment]
+1 just a list of all valid YAML keys and subkeys would be super helpful :smile: I might be able to construct that from the source code and put in a PR. 

Seems like the relevant struct that the YAML is unmarshalled into is [here](https://github.com/asteris-llc/hammer/blob/dbcae7a3a603e512bc31d86bb3ed3f1411cfd45b/hammer/package.go#L29-L73). Working on a PR now.
